lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    # plug RumblWeb.Log, msg: "Start of pipeline"
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth, repo: Rumbl.Repo
    # plug RumblWeb.Log, msg: "End of pipeline"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl/core/video.ex
defmodule Rumbl.Core.Video do
  use Ecto.Schema
  import Ecto.Changeset
  alias Rumbl.Core.Video

  @primary_key {:id, Rumbl.Permalink, autogenerate: true}
  schema "videos" do
    field :description, :string
    field :title, :string
    field :url, :string
    field :slug, :string
    belongs_to :user, RumblWeb.User
    belongs_to :category, Rumbl.Core.Category
    has_many :annotations, Rumbl.Annotation

    timestamps()
  end

  @doc false
  def changeset(%Video{} = video, attrs \\ %{}) do
    video
    |> cast(attrs, [:url, :title, :description, :category_id, :user_id])
    |> validate_required([:url, :title, :description])
    |> slugify_title()
    |> assoc_constraint(:category)
  end

  defp slugify_title(changeset) do
    if title = get_change(changeset, :title) do
      put_change(changeset, :slug, slugify(title))
    else
      changeset
    end
  end

  defp slugify(str) do
    str
    |> String.downcase()
    |> String.replace(~r/[^\w-]+/u, "-")
  end

  defimpl Phoenix.Param, for: Rumbl.Core.Video do
    def to_param(%{slug: slug, id: id}) do
      "#{id}-#{slug}"
    end
  end
end

lib/rumbl_web/controllers/video_controller.ex
defmodule RumblWeb.VideoController do
  use RumblWeb, :controller

  alias Rumbl.Repo
  alias Rumbl.Core
  alias Rumbl.Core.Video
  alias Rumbl.Core.Category

  plug :load_categories when action in [:new, :create, :edit, :update]

  defp load_categories(conn, _) do
    query =
      Category
      |> Category.alphabetical
      |> Category.names_and_ids
    categories = Repo.all query
    assign(conn, :categories, categories)
  end

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
      [conn, conn.params, conn.assigns.current_user])
  end

  def index(conn, _params, user) do
    videos = Core.list_user_videos(user)
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params, user) do
    changeset =
      user
      |> Ecto.build_assoc(:videos)
      |> Video.changeset()

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}, user) do
    case Core.create_video(user, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, user) do
    video = Core.get_user_video!(user, id)
    # video = Core.get_video!(id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}, user) do
    video = Core.get_user_video!(user, id)
    changeset = Core.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}, user) do
    video = Core.get_user_video!(user, id)

    case Core.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, user) do
    video = Core.get_user_video!(user, id)
    {:ok, _video} = Core.delete_video(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: video_path(conn, :index))
  end
end

lib/rumbl_web/views/video_view.ex
defmodule RumblWeb.VideoView do
  use RumblWeb, :view
end

lib/rumbl_web/templates/video/edit.html.eex
<h2>Edit Video</h2>

<%= render "form.html", Map.put(assigns, :action, video_path(@conn, :update, @video)) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/rumbl_web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :url, class: "control-label" %>
    <%= text_input f, :url, class: "form-control" %>
    <%= error_tag f, :url %>
  </div>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :category_id, "Category", class: "control-label" %>
    <%= select f, :category_id, @categories, class: "form-control",
                                prompt: "Choose a category" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/rumbl_web/templates/video/index.html.eex
<h2>Listing Videos</h2>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.url %></td>
      <td><%= video.title %></td>
      <td><%= video.description %></td>

      <td class="text-right">
        <span><%= link "Watch", to: watch_path(@conn, :show, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: video_path(@conn, :edit, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Video", to: video_path(@conn, :new) %></span>

lib/rumbl_web/templates/video/new.html.eex
<h2>New Video</h2>

<%= render "form.html", Map.put(assigns, :action, video_path(@conn, :create)) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/rumbl_web/templates/video/show.html.eex
<h2>Show Video</h2>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @video.description %>
  </li>

</ul>

<span><%= link "Edit", to: video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: video_path(@conn, :index) %></span>